name: bcetb
channels:
    - defaults
    - ambermd
    - conda-forge
dependencies:
    - python=3.7
    - pandas=0.23 # 0.23.1
    - scipy=1.1 # 1.1.0
    - matplotlib=2.2 # 2.2.2
    - jupyter
    - notebook
    - brewer2mpl=1.4
    - uncertainties=3.1 # 3.1.5
    - pytraj=2.0.4
    - mdtraj=1.9.3
    - pyemma=2.5.7
    - openpyxl=3.0
    - pip=3
    - numpy=1.14 # 1.14.5
    - pip:
      - pytc-fitter=1
